"""Cross-check: emit_yip vs a reduced reference package from the survey pipeline.

The reference package is generated by the design-survey pipeline itself with
small, seeded lists (see the workspace script that writes
``cds_eac1_yip_reduced.npz``). Both pipelines draw the identical pointing and
screen streams (numpy ``default_rng(0)``, same order) and evaluate the same
midpoint-sampled band, so every product is directly comparable, in ABSOLUTE
normalization (fitted scales come out at 1.0000): residuals reflect only the
propagation engines (multi-scale MFT vs the reference vortex).

Two precision regimes, measured 2026-07-05:

- Bright transmitted products (off-axis PSFs 2e-5/4e-5, sky 4.5e-5) sit on
  the engine floor of ~1e-4 established by the mono acceptance gates.
- Deep-null products (on-axis and barely-resolved stellar maps, ~9e-2) are
  the residuals of two 1e10-fold numerical cancellations: each engine's
  null structure is implementation-specific at the ~3e-11 contrast level,
  so pointwise shapes disagree at the 1e-1 level while the aggregate floor
  (max ratio) agrees to 3e-4. A mono control shows the same 9e-2, so the
  disagreement is engine-inherited, not chromatic. In contrast units the
  gap is ~3e-12: negligible for any yield quantity.
"""

import jax.numpy as jnp
import numpy as np
import pytest

from physicaloptix.core import Field, Grid, PlaneKind, Spectrum
from physicaloptix.elements import MultiScaleVortex, SampledOptic
from physicaloptix.path import OpticalPath, Stage
from physicaloptix.yip import emit_yip

_REFERENCE_CANDIDATES = (
    "tests/data/cds_eac1_yip_reduced.npz",
    # Development-workspace location written by the generation script.
    "../../hwo-mission-control/burn/physicaloptix-setup"  # internal-ref-ok
    "/scripts/eac1_dlux/data/cds_eac1_yip_reduced.npz",  # internal-ref-ok
)


@pytest.fixture(scope="module")
def reference():
    from pathlib import Path

    root = Path(__file__).parents[2]
    for candidate in _REFERENCE_CANDIDATES:
        path = (root / candidate).resolve()
        if path.exists():
            return np.load(path)
    pytest.skip("reduced cds YIP reference not found")


@pytest.fixture(scope="module")
def emitted(reference, eac1_cache, tmp_path_factory):
    z = eac1_cache
    meta = reference["meta"]
    center_um, bandpass, n_lam = meta[0], meta[1], int(meta[2])
    n_pointings, n_sky = int(meta[3]), int(meta[4])
    pixel_size, dims = float(meta[5]), int(meta[6])

    npup = int(z["meta"][0])
    charge = int(z["meta"][4])
    pupil_grid = Grid.pupil(npup)

    def pupil_optic(name):
        return SampledOptic(
            transmission=jnp.asarray(z[name], float),
            grid=pupil_grid,
            plane=PlaneKind.PUPIL,
        )

    core = OpticalPath(
        stages=(
            Stage("pupil_stop", pupil_optic("pupil_stop")),
            Stage("apodizer", pupil_optic("apodizer")),
            Stage(
                "vortex",
                MultiScaleVortex.build(
                    charge=charge, npup=npup, cap_num_airy0=npup // 2
                ),
            ),
            Stage("lyot", pupil_optic("lyot")),
        )
    )
    pupil = jnp.asarray(z["pupil"], float).astype(complex)
    field = Field(data=pupil, grid=pupil_grid, plane=PlaneKind.PUPIL)

    reference_nm = center_um * 1e3
    half = bandpass / 2.0
    return emit_yip(
        tmp_path_factory.mktemp("crosscheck"),
        core,
        field,
        science_grid=Grid.focal(dims, pixel_size),
        spectrum=Spectrum.midpoint_band(reference_nm, bandpass, n_lam),
        reference_wavelength_nm=reference_nm,
        offsets_lod=np.asarray(reference["offax_psf_offset_list"]),
        stellar_diams_lod=np.asarray(reference["stellar_intens_diam_list"]),
        n_pointings=n_pointings,
        n_sky_screens=n_sky,
        sky_band_nm=(reference_nm * (1 - half), reference_nm * (1 + half)),
        seed=0,
        diameter_m=7.2,
        inscribed_diameter_m=5.96,
        design_name="eac1-crosscheck",
    )


def scale_and_residual(ours, theirs):
    a = np.asarray(ours, float).ravel()
    b = np.asarray(theirs, float).ravel()
    scale = float((a * b).sum() / (a * a).sum())
    residual = float(np.linalg.norm(b - scale * a) / np.linalg.norm(b))
    return scale, residual


class TestCrossCheck:
    def test_offax_psfs_match(self, emitted, reference):
        """Bright transmitted fields: the ~1e-4 engine floor (measured 4e-5)."""
        for i in range(reference["offax_psf"].shape[0]):
            _, resid = scale_and_residual(
                emitted["offax_psf"][i], reference["offax_psf"][i]
            )
            assert resid < 2e-4, f"offset index {i}: residual {resid:.3e}"

    def test_stellar_intens_match(self, emitted, reference):
        """Deep-null maps: engine-specific null shapes (measured 9.5e-2 at
        d=0 and 9.2e-2 at d=0.1; a mono control reproduces the same 9e-2)."""
        for i in range(reference["stellar_intens"].shape[0]):
            _, resid = scale_and_residual(
                emitted["stellar_intens"][i], reference["stellar_intens"][i]
            )
            assert resid < 0.15, f"diameter index {i}: residual {resid:.3e}"

    def test_onaxis_floor_matches(self, emitted, reference):
        """The aggregate null floor is far tighter than the pointwise shape
        (measured max ratio 1.0003)."""
        ratio = float(
            np.asarray(emitted["stellar_intens"][0]).max()
            / np.asarray(reference["stellar_intens"][0]).max()
        )
        assert abs(ratio - 1.0) < 0.01, f"floor ratio {ratio:.6f}"

    def test_sky_trans_matches(self, emitted, reference):
        """Matched screens and band edges: engine floor (measured 4.5e-5)."""
        _, resid = scale_and_residual(emitted["sky_trans"], reference["sky_trans"])
        assert resid < 5e-4, f"sky residual {resid:.3e}"

    def test_absolute_normalization_matches(self, emitted, reference):
        """Bright products agree with the survey pipeline in ABSOLUTE value:
        fitted scales are 1 to ~5e-5 (deep-null maps excluded; their scale
        fit is biased by the shape mismatch)."""
        scales = [
            scale_and_residual(emitted["offax_psf"][i], reference["offax_psf"][i])[0]
            for i in range(reference["offax_psf"].shape[0])
        ]
        scales.append(
            scale_and_residual(emitted["sky_trans"], reference["sky_trans"])[0]
        )
        np.testing.assert_allclose(scales, 1.0, rtol=1e-3)
